2025-04-24 09:40:32,821 INFO    StreamThr :2207335 [internal.py:wandb_internal():85] W&B internal server running at pid: 2207335, started at: 2025-04-24 09:40:32.821192
2025-04-24 09:40:32,823 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: status
2025-04-24 09:40:32,829 INFO    WriterThread:2207335 [datastore.py:open_for_write():87] open: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/run-6imenzxp.wandb
2025-04-24 09:40:32,829 DEBUG   SenderThread:2207335 [sender.py:send():379] send: header
2025-04-24 09:40:32,829 DEBUG   SenderThread:2207335 [sender.py:send():379] send: run
2025-04-24 09:40:37,831 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:40:42,832 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:40:47,833 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:40:52,835 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:40:57,836 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:41:01,533 INFO    SenderThread:2207335 [dir_watcher.py:__init__():211] watching files in: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files
2025-04-24 09:41:01,534 INFO    SenderThread:2207335 [sender.py:_start_run_threads():1188] run started: 6imenzxp with start time 1745458832.82128
2025-04-24 09:41:01,534 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: status_report
2025-04-24 09:41:01,545 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: check_version
2025-04-24 09:41:01,546 DEBUG   SenderThread:2207335 [sender.py:send_request():406] send_request: check_version
2025-04-24 09:41:04,553 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: run_start
2025-04-24 09:41:04,574 DEBUG   HandlerThread:2207335 [system_info.py:__init__():26] System info init
2025-04-24 09:41:04,574 DEBUG   HandlerThread:2207335 [system_info.py:__init__():41] System info init done
2025-04-24 09:41:04,574 INFO    HandlerThread:2207335 [system_monitor.py:start():194] Starting system monitor
2025-04-24 09:41:04,575 INFO    SystemMonitor:2207335 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-24 09:41:04,575 INFO    HandlerThread:2207335 [system_monitor.py:probe():214] Collecting system info
2025-04-24 09:41:04,575 INFO    SystemMonitor:2207335 [interfaces.py:start():188] Started cpu monitoring
2025-04-24 09:41:04,576 INFO    SystemMonitor:2207335 [interfaces.py:start():188] Started disk monitoring
2025-04-24 09:41:04,577 INFO    SystemMonitor:2207335 [interfaces.py:start():188] Started gpu monitoring
2025-04-24 09:41:04,577 INFO    SystemMonitor:2207335 [interfaces.py:start():188] Started memory monitoring
2025-04-24 09:41:04,577 INFO    SystemMonitor:2207335 [interfaces.py:start():188] Started network monitoring
2025-04-24 09:41:04,601 DEBUG   HandlerThread:2207335 [system_info.py:probe():152] Probing system
2025-04-24 09:41:04,604 DEBUG   HandlerThread:2207335 [gitlib.py:_init_repo():56] git repository is invalid
2025-04-24 09:41:04,604 DEBUG   HandlerThread:2207335 [system_info.py:probe():200] Probing system done
2025-04-24 09:41:04,604 DEBUG   HandlerThread:2207335 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-134-generic-x86_64-with-glibc2.31', 'python': '3.9.21', 'heartbeatAt': '2025-04-24T01:41:04.601257', 'startedAt': '2025-04-24T01:40:32.812475', 'docker': None, 'cuda': None, 'args': ('task=mw-hammer',), 'state': 'running', 'program': '/home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/train_with_cprofile.py', 'codePathLocal': None, 'host': 'workstation', 'username': 'levi', 'executable': '/home/levi/anaconda3/envs/tdmpc2/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3500.102625, 'min': 800.0, 'max': 4950.0}, 'cpu_freq_per_core': [{'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 5300.0, 'min': 800.0, 'max': 5400.0}, {'current': 3400.0, 'min': 800.0, 'max': 5400.0}, {'current': 3902.463, 'min': 800.0, 'max': 5400.0}, {'current': 3400.0, 'min': 800.0, 'max': 5400.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}], 'disk': {'/': {'total': 456.8756866455078, 'used': 393.9691352844238}}, 'gpu': 'NVIDIA GeForce RTX 4090 D', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090 D', 'memory_total': 25757220864}], 'memory': {'total': 62.60572814941406}}
2025-04-24 09:41:04,604 INFO    HandlerThread:2207335 [system_monitor.py:probe():224] Finished collecting system info
2025-04-24 09:41:04,604 INFO    HandlerThread:2207335 [system_monitor.py:probe():227] Publishing system info
2025-04-24 09:41:04,604 DEBUG   HandlerThread:2207335 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2025-04-24 09:41:05,470 DEBUG   HandlerThread:2207335 [system_info.py:_save_conda():224] Saving conda packages done
2025-04-24 09:41:05,471 INFO    HandlerThread:2207335 [system_monitor.py:probe():229] Finished publishing system info
2025-04-24 09:41:05,477 DEBUG   SenderThread:2207335 [sender.py:send():379] send: files
2025-04-24 09:41:05,477 INFO    SenderThread:2207335 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-04-24 09:41:05,521 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: python_packages
2025-04-24 09:41:05,521 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: stop_status
2025-04-24 09:41:05,521 DEBUG   SenderThread:2207335 [sender.py:send_request():406] send_request: python_packages
2025-04-24 09:41:05,521 DEBUG   SenderThread:2207335 [sender.py:send_request():406] send_request: stop_status
2025-04-24 09:41:05,522 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:05,535 INFO    Thread-12 :2207335 [dir_watcher.py:_on_file_created():271] file/dir created: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/wandb-metadata.json
2025-04-24 09:41:05,535 INFO    Thread-12 :2207335 [dir_watcher.py:_on_file_created():271] file/dir created: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/conda-environment.yaml
2025-04-24 09:41:05,535 INFO    Thread-12 :2207335 [dir_watcher.py:_on_file_created():271] file/dir created: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/requirements.txt
2025-04-24 09:41:06,521 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:07,522 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:08,525 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:09,526 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:09,838 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-04-24 09:41:09,838 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:41:09,838 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:41:10,527 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:11,529 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:12,529 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:13,527 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:14,548 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:15,550 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:15,989 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-04-24 09:41:15,997 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:41:15,997 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:41:16,575 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:17,541 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:18,601 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:19,581 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:20,540 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
2025-04-24 09:41:20,540 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:41:20,540 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:41:20,541 INFO    wandb-upload_0:2207335 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2911, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-04-24 09:41:20,572 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:21,605 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:22,575 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:23,576 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:24,622 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:25,206 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
2025-04-24 09:41:25,206 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:41:25,206 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:41:25,588 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:26,601 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:27,649 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:28,617 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:29,596 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:30,596 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:31,597 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:32,597 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:33,597 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:34,597 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:35,772 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:36,169 WARNING FileStreamThread:2207335 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f258042cbb0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-04-24 09:41:36,169 INFO    SenderThread:2207335 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-04-24 09:41:36,169 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-04-24 09:41:36,170 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:41:36,170 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:41:36,763 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:37,765 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:38,765 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:39,767 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:40,772 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:41,769 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:42,797 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:43,805 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:44,876 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:45,915 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:46,940 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:47,913 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:48,927 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:49,932 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:50,923 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:51,928 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:52,936 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:53,589 WARNING FileStreamThread:2207335 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f258042cbb0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-04-24 09:41:53,942 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:54,331 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-04-24 09:41:54,332 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:41:54,332 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:41:54,948 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:55,939 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:56,925 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:57,925 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:58,925 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:41:59,925 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:00,925 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:01,926 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:02,926 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:03,926 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:04,577 DEBUG   SystemMonitor:2207335 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-24 09:42:04,926 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:05,926 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:06,371 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,407 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,472 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,531 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,590 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,646 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,705 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,762 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,821 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,880 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:06,926 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-24 09:42:06,939 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: partial_history
2025-04-24 09:42:08,592 WARNING FileStreamThread:2207335 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f258042cbb0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-04-24 09:42:08,646 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-24 09:42:13,648 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:18,649 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:23,650 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:24,010 WARNING FileStreamThread:2207335 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x7f258042cbb0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-04-24 09:42:28,651 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:33,652 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:35,379 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-04-24 09:42:35,379 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:42:35,379 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:42:38,654 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:43,656 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:48,658 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:53,625 WARNING FileStreamThread:2207335 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f258042cbb0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-04-24 09:42:53,660 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:42:58,661 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:03,663 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:08,664 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:13,665 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:18,667 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:23,668 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:26,426 WARNING FileStreamThread:2207335 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x7f258042cbb0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/6imenzxp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-04-24 09:43:28,669 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:33,671 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:38,672 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:41,998 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/6imenzxp/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250424%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250424T014105Z&X-Goog-Expires=86399&X-Goog-Signature=a81a7904be2d4e5f3116f9204375987c9bfe527c2e40cc0f257de618ddc7c423cf6a0cde5d99d0ecdcf4cd6b475c355df0ac4da040720aa8059e08a14f75dd0a2fd1880c432f75174be3897a677aec4f83c3d770aa6536639967748ab144e40c8cdde8ffaf05d5cb216db594d01b21e299553ada9c44993b615c84112c339a19774ef2140039afc08c07219535816ab286bde5a88b09bdfc56f8245079d65333c9ca46bbc4a9e2129b6203514711c9c70f63aeffc1d7f7ec45dc543b850c34c650bc88f967c2dae2311d7d4fef48316d787e51d7fef63bf1eb856b91055684ff36b44e302d5c205cb95ef9fe0b9e4bdd6a7cf1b93f1f98f19da34b930a8fe268&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
2025-04-24 09:43:42,007 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3579'}
2025-04-24 09:43:42,007 ERROR   wandb-upload_0:2207335 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-04-24 09:43:43,673 DEBUG   HandlerThread:2207335 [handler.py:handle_request():158] handle_request: keepalive
2025-04-24 09:43:44,610 INFO    memory    :2207335 [interfaces.py:monitor():138] Process proc.memory.rssMB has exited.
2025-04-24 09:43:44,611 DEBUG   SystemMonitor:2207335 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-24 09:43:44,611 DEBUG   SystemMonitor:2207335 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-24 09:43:45,995 WARNING StreamThr :2207335 [internal.py:is_dead():413] Internal process exiting, parent pid 2207226 disappeared
2025-04-24 09:43:45,995 ERROR   StreamThr :2207335 [internal.py:wandb_internal():151] Internal process shutdown.
2025-04-24 09:43:46,613 INFO    HandlerThread:2207335 [handler.py:finish():882] shutting down handler
2025-04-24 09:43:46,613 INFO    HandlerThread:2207335 [system_monitor.py:finish():203] Stopping system monitor
2025-04-24 09:43:46,613 INFO    HandlerThread:2207335 [interfaces.py:finish():200] Joined cpu monitor
2025-04-24 09:43:46,613 INFO    HandlerThread:2207335 [interfaces.py:finish():200] Joined disk monitor
2025-04-24 09:43:46,613 INFO    HandlerThread:2207335 [interfaces.py:finish():200] Joined gpu monitor
2025-04-24 09:43:46,613 INFO    HandlerThread:2207335 [interfaces.py:finish():200] Joined memory monitor
2025-04-24 09:43:46,613 INFO    HandlerThread:2207335 [interfaces.py:finish():200] Joined network monitor
2025-04-24 09:43:46,614 INFO    WriterThread:2207335 [datastore.py:close():296] close: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/run-6imenzxp.wandb
2025-04-24 09:44:18,630 INFO    SenderThread:2207335 [sender.py:finish():1608] shutting down sender
2025-04-24 09:44:18,630 INFO    SenderThread:2207335 [dir_watcher.py:finish():358] shutting down directory watcher
2025-04-24 09:44:19,563 INFO    SenderThread:2207335 [dir_watcher.py:finish():388] scan: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files
2025-04-24 09:44:19,563 INFO    SenderThread:2207335 [dir_watcher.py:finish():402] scan save: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/conda-environment.yaml conda-environment.yaml
2025-04-24 09:44:19,564 INFO    SenderThread:2207335 [dir_watcher.py:finish():402] scan save: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/config.yaml config.yaml
2025-04-24 09:44:19,564 INFO    SenderThread:2207335 [dir_watcher.py:finish():402] scan save: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/wandb-metadata.json wandb-metadata.json
2025-04-24 09:44:19,564 INFO    SenderThread:2207335 [dir_watcher.py:finish():402] scan save: /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/requirements.txt requirements.txt
2025-04-24 09:44:19,564 INFO    SenderThread:2207335 [file_pusher.py:finish():169] shutting down file pusher
2025-04-24 09:44:19,565 INFO    SenderThread:2207335 [file_pusher.py:join():175] waiting for file pusher
2025-04-24 09:44:20,722 INFO    wandb-upload_1:2207335 [upload_job.py:push():130] Uploaded file /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/conda-environment.yaml
2025-04-24 09:44:21,037 INFO    wandb-upload_2:2207335 [upload_job.py:push():130] Uploaded file /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/config.yaml
2025-04-24 09:44:21,112 INFO    wandb-upload_3:2207335 [upload_job.py:push():130] Uploaded file /home/levi/Desktop/MOORE-TDMPC/moore_tdmpc/logs/mw-hammer/42/moore-tdmpc2-mt30/wandb/run-20250424_094032-6imenzxp/files/requirements.txt
2025-04-24 09:46:19,505 INFO    wandb-upload_0:2207335 [upload_job.py:push():130] Uploaded file /tmp/tmp0j7m5kanwandb/roh5xebg-wandb-metadata.json
2025-04-24 09:46:20,195 INFO    SenderThread:2207335 [file_stream.py:finish():601] file stream finish called
2025-04-24 09:46:20,558 INFO    SenderThread:2207335 [file_stream.py:finish():605] file stream finish is done
