2025-05-13 21:11:07,151 INFO    StreamThr :608589 [internal.py:wandb_internal():85] W&B internal server running at pid: 608589, started at: 2025-05-13 21:11:07.150873
2025-05-13 21:11:07,151 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: status
2025-05-13 21:11:07,155 INFO    WriterThread:608589 [datastore.py:open_for_write():87] open: /home/levi/Desktop/MOORE-TDMPC/renew/logs/mw-reach/1/moore-tdmpc2-mt30/wandb/run-20250513_211107-3u01gn8a/run-3u01gn8a.wandb
2025-05-13 21:11:07,156 DEBUG   SenderThread:608589 [sender.py:send():379] send: header
2025-05-13 21:11:07,179 DEBUG   SenderThread:608589 [sender.py:send():379] send: run
2025-05-13 21:11:09,740 INFO    SenderThread:608589 [dir_watcher.py:__init__():211] watching files in: /home/levi/Desktop/MOORE-TDMPC/renew/logs/mw-reach/1/moore-tdmpc2-mt30/wandb/run-20250513_211107-3u01gn8a/files
2025-05-13 21:11:09,740 INFO    SenderThread:608589 [sender.py:_start_run_threads():1188] run started: 3u01gn8a with start time 1747141867.150892
2025-05-13 21:11:09,754 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: check_version
2025-05-13 21:11:09,754 DEBUG   SenderThread:608589 [sender.py:send_request():406] send_request: check_version
2025-05-13 21:11:12,760 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: status_report
2025-05-13 21:11:12,769 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: run_start
2025-05-13 21:11:12,801 DEBUG   HandlerThread:608589 [system_info.py:__init__():26] System info init
2025-05-13 21:11:12,801 DEBUG   HandlerThread:608589 [system_info.py:__init__():41] System info init done
2025-05-13 21:11:12,801 INFO    HandlerThread:608589 [system_monitor.py:start():194] Starting system monitor
2025-05-13 21:11:12,802 INFO    SystemMonitor:608589 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-05-13 21:11:12,802 INFO    HandlerThread:608589 [system_monitor.py:probe():214] Collecting system info
2025-05-13 21:11:12,803 INFO    SystemMonitor:608589 [interfaces.py:start():188] Started cpu monitoring
2025-05-13 21:11:12,804 INFO    SystemMonitor:608589 [interfaces.py:start():188] Started disk monitoring
2025-05-13 21:11:12,807 INFO    SystemMonitor:608589 [interfaces.py:start():188] Started gpu monitoring
2025-05-13 21:11:12,808 INFO    SystemMonitor:608589 [interfaces.py:start():188] Started memory monitoring
2025-05-13 21:11:12,809 INFO    SystemMonitor:608589 [interfaces.py:start():188] Started network monitoring
2025-05-13 21:11:12,881 DEBUG   HandlerThread:608589 [system_info.py:probe():152] Probing system
2025-05-13 21:11:12,892 DEBUG   HandlerThread:608589 [system_info.py:_probe_git():137] Probing git
2025-05-13 21:11:12,911 DEBUG   HandlerThread:608589 [system_info.py:_probe_git():145] Probing git done
2025-05-13 21:11:12,911 DEBUG   HandlerThread:608589 [system_info.py:probe():200] Probing system done
2025-05-13 21:11:12,912 DEBUG   HandlerThread:608589 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-136-generic-x86_64-with-glibc2.31', 'python': '3.9.21', 'heartbeatAt': '2025-05-13T13:11:12.881480', 'startedAt': '2025-05-13T13:11:07.142020', 'docker': None, 'cuda': None, 'args': ('task=mw-reach',), 'state': 'running', 'program': '/home/levi/Desktop/MOORE-TDMPC/renew/train_with_cprofile.py', 'codePathLocal': None, 'codePath': 'renew/train_with_cprofile.py', 'git': {'remote': 'https://github.com/glue25/Multi-Task-MBRL', 'commit': '8a8f62177b4e3af0a42363999c165f422a90b325'}, 'email': 'sc_levi@163.com', 'root': '/home/levi/Desktop/MOORE-TDMPC', 'host': 'workstation', 'username': 'levi', 'executable': '/home/levi/anaconda3/envs/tdmpc2/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3302.0063333333333, 'min': 800.0, 'max': 4950.0}, 'cpu_freq_per_core': [{'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 1100.032, 'min': 800.0, 'max': 5400.0}, {'current': 3400.0, 'min': 800.0, 'max': 5400.0}, {'current': 3400.0, 'min': 800.0, 'max': 5400.0}, {'current': 3400.0, 'min': 800.0, 'max': 5400.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 5300.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}, {'current': 3400.0, 'min': 800.0, 'max': 4200.0}], 'disk': {'/': {'total': 456.8756866455078, 'used': 397.9297523498535}}, 'gpu': 'NVIDIA GeForce RTX 4090 D', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090 D', 'memory_total': 25757220864}], 'memory': {'total': 62.605716705322266}}
2025-05-13 21:11:12,912 INFO    HandlerThread:608589 [system_monitor.py:probe():224] Finished collecting system info
2025-05-13 21:11:12,912 INFO    HandlerThread:608589 [system_monitor.py:probe():227] Publishing system info
2025-05-13 21:11:12,912 DEBUG   HandlerThread:608589 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2025-05-13 21:11:13,742 INFO    Thread-12 :608589 [dir_watcher.py:_on_file_created():271] file/dir created: /home/levi/Desktop/MOORE-TDMPC/renew/logs/mw-reach/1/moore-tdmpc2-mt30/wandb/run-20250513_211107-3u01gn8a/files/conda-environment.yaml
2025-05-13 21:11:13,779 DEBUG   HandlerThread:608589 [system_info.py:_save_conda():224] Saving conda packages done
2025-05-13 21:11:13,779 INFO    HandlerThread:608589 [system_monitor.py:probe():229] Finished publishing system info
2025-05-13 21:11:13,782 DEBUG   SenderThread:608589 [sender.py:send():379] send: files
2025-05-13 21:11:13,782 INFO    SenderThread:608589 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-05-13 21:11:13,825 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: python_packages
2025-05-13 21:11:13,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: stop_status
2025-05-13 21:11:13,826 DEBUG   SenderThread:608589 [sender.py:send_request():406] send_request: python_packages
2025-05-13 21:11:13,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:13,826 DEBUG   SenderThread:608589 [sender.py:send_request():406] send_request: stop_status
2025-05-13 21:11:14,741 INFO    Thread-12 :608589 [dir_watcher.py:_on_file_created():271] file/dir created: /home/levi/Desktop/MOORE-TDMPC/renew/logs/mw-reach/1/moore-tdmpc2-mt30/wandb/run-20250513_211107-3u01gn8a/files/requirements.txt
2025-05-13 21:11:14,741 INFO    Thread-12 :608589 [dir_watcher.py:_on_file_created():271] file/dir created: /home/levi/Desktop/MOORE-TDMPC/renew/logs/mw-reach/1/moore-tdmpc2-mt30/wandb/run-20250513_211107-3u01gn8a/files/wandb-metadata.json
2025-05-13 21:11:14,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:15,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:16,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:17,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:18,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:19,826 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:20,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:21,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:22,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:23,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:24,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:25,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:26,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:27,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:28,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:29,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:30,827 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:31,828 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:32,828 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:33,804 INFO    wandb-upload_0:608589 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)
2025-05-13 21:11:33,828 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:34,828 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:35,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:35,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:35,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:35,881 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:35,928 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:35,955 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:35,993 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:36,030 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:36,067 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:36,105 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:36,143 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:36,182 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:11:36,829 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:37,829 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:38,829 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:39,829 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:40,829 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:41,829 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:42,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:43,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:44,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:45,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:46,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:47,800 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:11:47,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:48,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:49,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:50,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:51,830 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:52,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:53,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:54,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:55,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:56,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:57,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:58,223 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:11:58,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:11:59,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:00,831 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:01,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:02,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:03,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:04,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:05,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:06,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:07,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:08,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:09,832 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:10,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:11,016 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:12:11,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:12,809 DEBUG   SystemMonitor:608589 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-05-13 21:12:12,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:13,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:14,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:15,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:16,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:17,821 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
2025-05-13 21:12:17,821 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:12:17,821 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:12:17,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:18,833 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:19,333 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
2025-05-13 21:12:19,333 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:12:19,333 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:12:19,834 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:20,834 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:21,834 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:22,053 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
2025-05-13 21:12:22,054 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:12:22,054 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:12:22,054 INFO    wandb-upload_0:608589 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2911, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-05-13 21:12:22,834 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:23,834 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:24,834 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:25,834 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:26,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:27,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:28,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:29,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:30,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:31,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:32,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:33,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:34,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:35,378 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-13 21:12:35,378 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:12:35,378 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:12:35,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:36,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:37,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:38,835 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:39,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:40,560 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:12:40,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:41,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:42,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:43,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:44,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:45,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:46,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:47,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:48,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:49,836 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:50,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:51,448 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-13 21:12:51,448 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:12:51,448 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:12:51,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:52,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:53,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:54,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:55,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:56,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:57,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:58,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:12:59,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:00,837 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:01,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:02,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:03,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:04,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:05,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:06,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:07,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:07,938 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:13:08,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:09,838 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:10,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:11,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:12,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:13,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:14,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:15,114 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:13:15,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:16,661 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-13 21:13:16,661 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:13:16,661 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:13:16,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:17,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:18,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:19,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:20,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:21,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:22,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:23,839 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:24,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:25,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:25,962 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:13:26,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:27,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:28,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:29,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:30,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:31,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:32,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:33,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:34,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:35,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:36,840 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:37,139 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:13:37,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:38,322 INFO    SenderThread:608589 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/levi/anaconda3/envs/tdmpc2/lib/python3.9/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-13 21:13:38,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:39,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:40,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:41,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:42,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:43,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:44,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:45,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:46,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:47,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:48,207 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:13:48,504 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:13:48,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:49,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:50,841 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:51,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:52,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:53,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:54,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:55,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:56,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:57,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:58,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:59,293 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:13:59,842 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:13:59,984 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-13 21:13:59,984 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:13:59,984 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:14:00,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:01,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:02,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:03,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:04,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:05,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:06,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:07,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:08,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:09,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:10,339 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:14:10,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:11,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:12,843 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:13,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:14,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:15,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:16,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:17,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:18,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:19,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:20,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:21,370 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:14:21,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:22,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:23,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:24,844 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:25,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:26,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:27,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:28,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:29,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:30,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:31,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:32,408 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:14:32,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:33,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:34,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:35,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:36,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:37,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:38,845 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:39,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:40,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:41,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:42,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:43,486 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:14:43,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:44,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:45,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:46,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:47,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:48,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:49,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:50,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:51,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:52,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:53,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:54,526 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:14:54,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:55,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:56,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:57,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:58,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:14:59,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:00,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:01,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:02,847 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:03,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:04,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:05,526 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:15:05,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:06,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:07,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:08,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:09,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:10,777 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:15:10,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:11,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:12,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:13,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:14,848 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:15,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:16,610 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:15:16,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:17,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:18,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:19,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:20,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:21,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:22,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:23,394 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-13 21:15:23,394 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:15:23,394 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:15:23,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:24,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:25,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:26,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:27,741 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:15:27,849 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:28,850 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:29,850 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:30,850 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:31,850 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:32,850 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:33,850 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:34,850 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:35,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:36,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:37,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:38,643 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:15:38,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:39,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:40,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:41,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:42,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:43,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:44,851 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:45,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:46,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:47,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:48,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:49,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:49,971 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:15:50,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:51,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:52,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:53,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:54,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:55,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:56,852 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:57,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:58,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:15:59,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:00,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:01,415 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:16:01,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:02,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:03,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:04,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:05,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:06,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:07,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:08,853 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:09,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:10,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:11,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:12,653 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:16:12,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:13,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:14,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:15,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:16,854 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:17,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:18,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:19,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:20,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:21,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:22,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:23,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:24,307 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:16:24,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:25,855 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:26,856 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:27,856 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:28,856 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:29,856 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:30,856 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:31,856 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:32,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:33,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:34,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:35,483 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:16:35,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:36,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:37,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:38,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:39,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:40,857 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:41,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:42,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:43,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:44,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:45,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:46,745 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:16:46,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:47,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:48,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:49,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:50,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:51,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:52,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:53,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:54,858 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:55,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:56,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:57,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:57,960 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:16:58,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:16:59,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:00,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:01,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:02,859 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:03,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:04,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:05,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:06,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:07,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:08,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:09,145 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:17:09,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:10,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:11,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:12,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:13,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:14,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:15,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:16,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:17,860 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:18,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:19,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:20,324 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:17:20,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:21,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:22,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:23,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:24,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:25,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:26,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:27,861 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:28,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:29,517 WARNING FileStreamThread:608589 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa0e4a20fa0>>, args: ('https://api.wandb.ai/files/OA-MBRL/moore-tdmpc2/3u01gn8a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2025-05-13 21:17:29,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:30,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:31,471 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:17:31,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:32,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:33,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:34,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:35,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:36,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:37,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:38,862 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:39,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:40,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:41,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:42,672 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:17:42,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:43,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:44,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:45,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:46,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:47,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:48,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:49,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:50,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:51,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:52,863 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:53,846 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:17:53,888 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:54,209 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/OA-MBRL/moore-tdmpc2/3u01gn8a/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250513T131216Z&X-Goog-Expires=86399&X-Goog-Signature=6275f1aaef994c0f7eae17ba04fa016f9af41ca8d4cb37dde938ce7307908c7ec218e19b5bd9bae1455ce65e3952e2f5949465bdfde39e962cc03ad3a9becf80908483317d13c1e937e479e2f6dcddd50192035fd206221cafb8ba22371768017fd0fbfe219f2c3373a07ed69d9ef19f4c4f0cb0e86201947c9434bb620b01f18a0e95a5642071ef8101d30ce2883911c5bdc86156b517bf2bc40f7bae3e06af192c28c9f4656745645525adb7442f31a59819d816c43b5768ee3ecaf7c3f5b2322397b9101dccd95856a572516bd6baeb26a1cd7092796d671ac54f8d62248538530b47ce272503d28613430550a7d580226c140992d5c1f7f493257a99d31b&X-Goog-SignedHeaders=host&X-User=levi1024: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-13 21:17:54,209 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3850'}
2025-05-13 21:17:54,209 ERROR   wandb-upload_0:608589 [internal_api.py:upload_file():2891] upload_file response body: ''
2025-05-13 21:17:54,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:55,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:56,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:57,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:58,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:17:59,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:00,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:01,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:02,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:03,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:04,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:05,116 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:18:05,864 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:06,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:07,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:08,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:09,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:10,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:11,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:12,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:13,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:14,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:15,865 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:16,347 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:18:16,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:17,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:18,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:19,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:20,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:21,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:22,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:23,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:24,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:25,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:26,866 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:27,572 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:18:27,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:28,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:29,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:30,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:31,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:32,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:33,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:34,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:35,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:36,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:37,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:38,819 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:18:38,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:39,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:40,867 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:41,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:42,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:43,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:44,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:45,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:46,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:47,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:48,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:49,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:50,008 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:18:50,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:51,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:52,868 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:53,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:54,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:55,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:56,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:57,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:58,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:18:59,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:00,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:01,335 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:19:01,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:02,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:03,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:04,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:05,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:06,869 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:07,870 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:08,870 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:09,870 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:10,870 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:11,870 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:12,209 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: partial_history
2025-05-13 21:19:12,870 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:13,870 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: internal_messages
2025-05-13 21:19:15,355 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: poll_exit
2025-05-13 21:19:20,357 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: keepalive
2025-05-13 21:19:25,359 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: keepalive
2025-05-13 21:19:30,361 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: keepalive
2025-05-13 21:19:35,363 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: keepalive
2025-05-13 21:19:40,364 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: keepalive
2025-05-13 21:19:45,366 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: keepalive
2025-05-13 21:19:50,368 DEBUG   HandlerThread:608589 [handler.py:handle_request():158] handle_request: keepalive
